#!/usr/bin/env python3
"""Parse ns-3 network telemetry into stable CSV/JSON experiment outputs.

FlowMonitor is useful for traffic generated by ns-3 IP stacks.  The platform's
real Modbus traffic is injected by Linux namespaces through TapBridge and can be
absent from FlowMonitor because it never receives an ns-3 FlowProbe tag.  The
generated point-to-point link snapshot is therefore parsed as an independent,
device-level source and must not be confused with application RTT.
"""
from __future__ import annotations

import csv
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Iterable


NETWORK_COLUMNS = [
    "metric_source",
    "scope",
    "flow_id",
    "link",
    "direction",
    "source",
    "target",
    "source_ip",
    "destination_ip",
    "protocol",
    "source_port",
    "destination_port",
    "simulation_time_s",
    "configured_delay",
    "configured_data_rate",
    "configured_delay_ms",
    "configured_data_rate_bps",
    "configured_error_rate",
    "configured_error_unit",
    "tx_packets",
    "rx_packets",
    "lost_packets",
    "drop_packets",
    "tx_bytes",
    "rx_bytes",
    "delay_samples",
    "mean_delay_ms",
    "max_delay_ms",
    "mean_jitter_ms",
    "throughput_bps",
    "duration_s",
    "packet_loss_rate",
    "delay_error_ms",
    "delay_error_percent",
    "loss_error",
    "throughput_utilization",
    "pending_packets",
    "times_forwarded",
]

_TIME_RE = re.compile(
    r"^\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s*(fs|ps|ns|us|ms|s)\s*$"
)
_TIME_FACTORS = {"fs": 1e-15, "ps": 1e-12, "ns": 1e-9, "us": 1e-6, "ms": 1e-3, "s": 1.0}
_PROTOCOLS = {6: "TCP", 17: "UDP"}
_DATA_RATE_RE = re.compile(
    r"^\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s*([kmgt]?bps)\s*$",
    flags=re.IGNORECASE,
)
_DATA_RATE_FACTORS = {"bps": 1.0, "kbps": 1e3, "mbps": 1e6, "gbps": 1e9, "tbps": 1e12}


def parse_ns3_time(value: str | None) -> float:
    """Convert an ns-3 XML time such as ``+1250000ns`` to seconds."""
    if value is None:
        return 0.0
    match = _TIME_RE.fullmatch(str(value))
    if match is None:
        raise ValueError(f"Unsupported ns-3 time value: {value!r}")
    return float(match.group(1)) * _TIME_FACTORS[match.group(2)]


def parse_data_rate_bps(value: str | None) -> float:
    """Convert an ns-3 data rate such as ``10Mbps`` to bits per second."""
    if value is None:
        raise ValueError("data rate is missing")
    match = _DATA_RATE_RE.fullmatch(str(value))
    if match is None:
        raise ValueError(f"Unsupported ns-3 data rate: {value!r}")
    return float(match.group(1)) * _DATA_RATE_FACTORS[match.group(2).lower()]


def _int(value: Any, default: int = 0) -> int:
    if value in (None, ""):
        return default
    return int(float(value))


def _float(value: Any, default: float = 0.0) -> float:
    if value in (None, ""):
        return default
    return float(value)


def _direction(source_port: int, destination_port: int) -> str:
    if destination_port == 502:
        return "request"
    if source_port == 502:
        return "response"
    return "other"


def _drop_count(flow: ET.Element) -> int:
    return sum(_int(item.get("number")) for item in flow.findall("packetsDropped"))


def parse_flow_monitor_xml(path: Path | str) -> list[dict[str, Any]]:
    """Return one normalized row per IPv4 FlowMonitor flow.

    An empty ``FlowStats`` element returns an empty list.  In particular, this
    function never invents zero-valued Modbus flows for a TapBridge run.
    """
    path = Path(path)
    root = ET.parse(path).getroot()
    classifiers = {
        str(item.get("flowId")): item
        for item in root.findall("./Ipv4FlowClassifier/Flow")
        if item.get("flowId") is not None
    }
    rows: list[dict[str, Any]] = []
    for flow in root.findall("./FlowStats/Flow"):
        flow_id = str(flow.get("flowId", ""))
        classifier = classifiers.get(flow_id)
        if classifier is None:
            # Without a five-tuple this is not a trustworthy flow record.
            continue

        tx_packets = _int(flow.get("txPackets"))
        rx_packets = _int(flow.get("rxPackets"))
        tx_bytes = _int(flow.get("txBytes"))
        rx_bytes = _int(flow.get("rxBytes"))
        lost_packets = _int(flow.get("lostPackets"))
        delay_sum_s = parse_ns3_time(flow.get("delaySum"))
        jitter_sum_s = parse_ns3_time(flow.get("jitterSum"))
        first_tx_s = parse_ns3_time(flow.get("timeFirstTxPacket"))
        last_rx_s = parse_ns3_time(flow.get("timeLastRxPacket"))
        duration_s = max(0.0, last_rx_s - first_tx_s) if rx_packets else 0.0
        source_port = _int(classifier.get("sourcePort"))
        destination_port = _int(classifier.get("destinationPort"))
        protocol_number = _int(classifier.get("protocol"))
        delivery_missing = max(0, tx_packets - rx_packets)

        rows.append(
            {
                "metric_source": "flow_monitor",
                "scope": "flow",
                "flow_id": _int(flow_id),
                "link": "",
                "direction": _direction(source_port, destination_port),
                "source": classifier.get("sourceAddress", ""),
                "target": classifier.get("destinationAddress", ""),
                "source_ip": classifier.get("sourceAddress", ""),
                "destination_ip": classifier.get("destinationAddress", ""),
                "protocol": _PROTOCOLS.get(protocol_number, str(protocol_number)),
                "source_port": source_port,
                "destination_port": destination_port,
                "simulation_time_s": last_rx_s,
                "configured_delay": "",
                "configured_data_rate": "",
                "configured_delay_ms": "",
                "configured_data_rate_bps": "",
                "configured_error_rate": "",
                "configured_error_unit": "",
                "tx_packets": tx_packets,
                "rx_packets": rx_packets,
                "lost_packets": lost_packets,
                "drop_packets": _drop_count(flow),
                "tx_bytes": tx_bytes,
                "rx_bytes": rx_bytes,
                "delay_samples": rx_packets,
                "mean_delay_ms": delay_sum_s * 1000.0 / rx_packets if rx_packets else None,
                "max_delay_ms": parse_ns3_time(flow.get("maxDelay")) * 1000.0 if rx_packets else None,
                "mean_jitter_ms": jitter_sum_s * 1000.0 / (rx_packets - 1) if rx_packets > 1 else None,
                "throughput_bps": 8.0 * rx_bytes / duration_s if duration_s > 0 else None,
                "duration_s": duration_s,
                "packet_loss_rate": delivery_missing / tx_packets if tx_packets else None,
                "delay_error_ms": None,
                "delay_error_percent": None,
                "loss_error": None,
                "throughput_utilization": None,
                "pending_packets": max(0, delivery_missing - lost_packets),
                "times_forwarded": _int(flow.get("timesForwarded")),
            }
        )
    return rows


def parse_link_metrics_csv(path: Path | str) -> list[dict[str, Any]]:
    """Parse the latest cumulative P2P link snapshot into normalized rows."""
    path = Path(path)
    with path.open(newline="", encoding="utf-8") as handle:
        source_rows = list(csv.DictReader(handle))

    rows: list[dict[str, Any]] = []
    for item in source_rows:
        tx_packets = _int(item.get("tx_packets"))
        rx_packets = _int(item.get("rx_packets"))
        drop_packets = _int(item.get("drop_packets"))
        rx_bytes = _int(item.get("rx_bytes"))
        simulation_time_s = _float(item.get("simulation_time_s"))
        delay_samples = _int(item.get("delay_samples"))
        mean_delay_ms = _float(item.get("mean_delay_ms")) if delay_samples else None
        configured_delay = item.get("configured_delay", "")
        configured_data_rate = item.get("configured_data_rate", "")
        try:
            configured_delay_ms: float | None = parse_ns3_time(configured_delay) * 1000.0
        except ValueError:
            configured_delay_ms = None
        try:
            configured_data_rate_bps: float | None = parse_data_rate_bps(configured_data_rate)
        except ValueError:
            configured_data_rate_bps = None
        raw_error_rate = item.get("configured_error_rate")
        configured_error_rate = (
            _float(raw_error_rate) if raw_error_rate not in (None, "") else None
        )
        configured_error_unit = str(item.get("configured_error_unit", "") or "").strip().lower()
        packet_loss_rate = drop_packets / tx_packets if tx_packets else None
        delay_error_ms = (
            abs(mean_delay_ms - configured_delay_ms)
            if mean_delay_ms is not None and configured_delay_ms is not None
            else None
        )
        loss_error = (
            abs(packet_loss_rate - configured_error_rate)
            if packet_loss_rate is not None and configured_error_unit == "packet"
            else None
        )
        rows.append(
            {
                "metric_source": "link_trace",
                "scope": "link_direction",
                "flow_id": "",
                "link": item.get("link", ""),
                "direction": item.get("direction", ""),
                "source": item.get("source", ""),
                "target": item.get("target", ""),
                "source_ip": "",
                "destination_ip": "",
                "protocol": "",
                "source_port": "",
                "destination_port": "",
                "simulation_time_s": simulation_time_s,
                "configured_delay": configured_delay,
                "configured_data_rate": configured_data_rate,
                "configured_delay_ms": configured_delay_ms,
                "configured_data_rate_bps": configured_data_rate_bps,
                "configured_error_rate": configured_error_rate,
                "configured_error_unit": configured_error_unit,
                "tx_packets": tx_packets,
                "rx_packets": rx_packets,
                # Explicit device/error-model drops are authoritative.  Pending
                # packets are reported separately and are not declared lost.
                "lost_packets": drop_packets,
                "drop_packets": drop_packets,
                "tx_bytes": _int(item.get("tx_bytes")),
                "rx_bytes": rx_bytes,
                "delay_samples": delay_samples,
                "mean_delay_ms": mean_delay_ms,
                "max_delay_ms": _float(item.get("max_delay_ms")) if delay_samples else None,
                "mean_jitter_ms": None,
                "throughput_bps": 8.0 * rx_bytes / simulation_time_s if simulation_time_s > 0 else None,
                "duration_s": simulation_time_s,
                "packet_loss_rate": packet_loss_rate,
                "delay_error_ms": delay_error_ms,
                "delay_error_percent": (
                    delay_error_ms / configured_delay_ms * 100.0
                    if delay_error_ms is not None and configured_delay_ms not in (None, 0.0)
                    else None
                ),
                "loss_error": loss_error,
                "throughput_utilization": (
                    (8.0 * rx_bytes / simulation_time_s) / configured_data_rate_bps
                    if simulation_time_s > 0 and configured_data_rate_bps not in (None, 0.0)
                    else None
                ),
                "pending_packets": _int(item.get("pending_packets")),
                "times_forwarded": "",
            }
        )
    return rows


def _aggregate_source(rows: Iterable[dict[str, Any]]) -> dict[str, Any]:
    rows = list(rows)
    tx_packets = sum(_int(row.get("tx_packets")) for row in rows)
    rx_packets = sum(_int(row.get("rx_packets")) for row in rows)
    drops = sum(_int(row.get("drop_packets")) for row in rows)
    lost = sum(_int(row.get("lost_packets")) for row in rows)
    delay_samples = sum(_int(row.get("delay_samples")) for row in rows)
    weighted_delay = sum(
        _float(row.get("mean_delay_ms")) * _int(row.get("delay_samples"))
        for row in rows
        if row.get("mean_delay_ms") is not None
    )
    throughputs = [float(row["throughput_bps"]) for row in rows if row.get("throughput_bps") is not None]
    delay_errors = [float(row["delay_error_ms"]) for row in rows if row.get("delay_error_ms") is not None]
    delay_error_percentages = [
        float(row["delay_error_percent"])
        for row in rows
        if row.get("delay_error_percent") is not None
    ]
    loss_errors = [float(row["loss_error"]) for row in rows if row.get("loss_error") is not None]
    return {
        "row_count": len(rows),
        "tx_packets": tx_packets,
        "rx_packets": rx_packets,
        "lost_packets": lost,
        "drop_packets": drops,
        "delay_samples": delay_samples,
        "mean_delay_ms": weighted_delay / delay_samples if delay_samples else None,
        "packet_loss_rate": lost / tx_packets if tx_packets else None,
        "throughput_bps_sum": sum(throughputs) if throughputs else None,
        "mean_abs_delay_error_ms": sum(delay_errors) / len(delay_errors) if delay_errors else None,
        "max_abs_delay_error_ms": max(delay_errors) if delay_errors else None,
        "mean_delay_error_percent": (
            sum(delay_error_percentages) / len(delay_error_percentages)
            if delay_error_percentages
            else None
        ),
        "mean_loss_error": sum(loss_errors) / len(loss_errors) if loss_errors else None,
        "max_loss_error": max(loss_errors) if loss_errors else None,
    }


def write_network_outputs(
    rows: list[dict[str, Any]],
    output_csv: Path | str,
    aggregate_json: Path | str,
    *,
    warnings: list[str] | None = None,
) -> dict[str, Any]:
    output_csv = Path(output_csv)
    aggregate_json = Path(aggregate_json)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    aggregate_json.parent.mkdir(parents=True, exist_ok=True)

    with output_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=NETWORK_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({column: row.get(column, "") for column in NETWORK_COLUMNS})

    sources = sorted({str(row.get("metric_source", "")) for row in rows if row.get("metric_source")})
    summary = {
        "status": "ok" if rows else "no_data",
        "row_count": len(rows),
        "warnings": list(warnings or []),
        "by_source": {
            source: _aggregate_source(row for row in rows if row.get("metric_source") == source)
            for source in sources
        },
    }
    aggregate_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return summary


def analyze_network(
    *,
    flow_monitor_xml: Path | str | None,
    link_metrics_csv: Path | str | None,
    output_csv: Path | str,
    aggregate_json: Path | str,
) -> dict[str, Any]:
    """Parse every available source and write ``network.csv`` plus JSON summary."""
    rows: list[dict[str, Any]] = []
    warnings: list[str] = []

    if flow_monitor_xml is not None:
        path = Path(flow_monitor_xml)
        if path.exists():
            flow_rows = parse_flow_monitor_xml(path)
            rows.extend(flow_rows)
            if not flow_rows:
                warnings.append(
                    "FlowMonitor has no classified IPv4 flows; external TapBridge traffic may be absent. "
                    "Use link_trace and application RTT metrics."
                )
        else:
            warnings.append(f"FlowMonitor XML not found: {path}")

    if link_metrics_csv is not None:
        path = Path(link_metrics_csv)
        if path.exists():
            link_rows = parse_link_metrics_csv(path)
            rows.extend(link_rows)
            if not link_rows:
                warnings.append(f"Link metrics CSV contains no rows: {path}")
        else:
            warnings.append(f"Link metrics CSV not found: {path}")

    return write_network_outputs(rows, output_csv, aggregate_json, warnings=warnings)
